spring:
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.196.77.250:3306/user?characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
      username: root
      password: root
      connection-timeout: 500
      idle-timeout: 600000
      initialization-fail-timeout: 1000
      login-timeout: 500
      max-lifetime: 1800000
      maximum-pool-size: 2
      minimum-idle: 1
      validation-timeout: 1000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
    database: mysql
#showSql
logging:
  level:
    com:
      example:
        mapper: debug