spring:
  application:
    name: provider

rocketmq:
  nameServer: 116.196.77.250:9876
  producer:
    group: my-group
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-next-server: true
    retry-times-when-send-async-failed: 0
    retry-times-when-send-failed: 2
    send-message-timeout: 3000
server:
  port: 9999